# Based on https://github.com/hvr/multi-ghc-travis

language: c

# Explicitly request container-based infrastructure.
sudo: false

matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.4.2
      addons: {apt: {packages: [cabal-install-1.16, ghc-7.4.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.16 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.16, ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24, ghc-8.0.1], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head, ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=1.24 GHCVER=8.0.1
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - set -e;
    for pkg in
        instances-bytestring
        instances-case-insensitive
        instances-new-base
        instances-text
        instances-unordered-containers
        instances-vector
        extra;
    do
        echo; echo;
        echo "$pkg:";
        cd "$pkg";
        cabal install --only-dependencies
            -fwith-bytestring
            -fwith-case-insensitive
            -fwith-containers
            -fwith-dlist
            -fwith-text
            -fwith-old-locale
            -fwith-unordered-containers
            -fwith-vector;
        cd "..";
    done

script:
  - set -e;
    for pkg in
        instances-bytestring
        instances-case-insensitive
        instances-new-base
        instances-text
        instances-unordered-containers
        instances-vector
        extra;
    do
        echo; echo;
        echo "$pkg:";
        cd "$pkg";
        cabal install
            -fwith-bytestring
            -fwith-case-insensitive
            -fwith-containers
            -fwith-dlist
            -fwith-text
            -fwith-old-locale
            -fwith-unordered-containers
            -fwith-vector;
        cd "..";
    done

  # Following tests if sdist packages are created correctly.
  - set -e;
    for pkg in
        instances-bytestring
        instances-case-insensitive
        instances-new-base
        instances-text
        instances-unordered-containers
        instances-vector
        extra;
    do
        echo; echo;
        echo "$pkg:";
        cd "$pkg";
        cabal configure;
        cabal sdist | sed -rn '$s/^[^:]+:\s+//p' | xargs cabal install
            -fwith-bytestring
            -fwith-case-insensitive
            -fwith-containers
            -fwith-dlist
            -fwith-text
            -fwith-old-locale
            -fwith-unordered-containers
            -fwith-vector;
        cd "..";
    done
